// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bXDe5fyotRxKZ7X2HxyCowF5snUBAw8',
    appId: '1:695285418623:web:0d6e734fb1b4c9351dcd4a',
    messagingSenderId: '695285418623',
    projectId: 'food-app-6c3b5',
    authDomain: 'food-app-6c3b5.firebaseapp.com',
    storageBucket: 'food-app-6c3b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq5wLe1P_67gf3654culHWLl6_8Ae89Ss',
    appId: '1:695285418623:android:ee7f84142cb084951dcd4a',
    messagingSenderId: '695285418623',
    projectId: 'food-app-6c3b5',
    storageBucket: 'food-app-6c3b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAX_TFPxKOCL_5g-ObeB0zBKV4SfbphPI',
    appId: '1:695285418623:ios:b51f6d6ab8b0d6601dcd4a',
    messagingSenderId: '695285418623',
    projectId: 'food-app-6c3b5',
    storageBucket: 'food-app-6c3b5.appspot.com',
    iosClientId: '695285418623-1ll3ch1l26eacblipoje5krho5snsdh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAX_TFPxKOCL_5g-ObeB0zBKV4SfbphPI',
    appId: '1:695285418623:ios:b51f6d6ab8b0d6601dcd4a',
    messagingSenderId: '695285418623',
    projectId: 'food-app-6c3b5',
    storageBucket: 'food-app-6c3b5.appspot.com',
    iosClientId: '695285418623-1ll3ch1l26eacblipoje5krho5snsdh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
